name: CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: teslaopunix/getjobs_front:latest
          build-args: |
            NEXT_PUBLIC_BACK_AUTH=${{ secrets.NEXT_PUBLIC_BACK_AUTH }}
            NEXT_PUBLIC_BACK_MAIN=${{ secrets.NEXT_PUBLIC_BACK_MAIN }}
            NEXT_PUBLIC_RAZORPAY_KEY_ID=${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}

      - name: Disable SSH Host Key Checking
        run: |
           mkdir -p ~/.ssh
           echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            docker pull teslaopunix/getjobs_front:latest
            docker stop gj-front || true
            docker rm gj-front || true
            docker run -d \
              --name gj-front \
              -p 3000:3000 \
              --env NEXT_PUBLIC_BACK_AUTH=${{ secrets.NEXT_PUBLIC_BACK_AUTH }} \
              --env NEXT_PUBLIC_BACK_MAIN=${{ secrets.NEXT_PUBLIC_BACK_MAIN }} \
              --env NEXT_PUBLIC_RAZORPAY_KEY_ID=${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }} \
              teslaopunix/getjobs_front:latest
              
            docker image prune -f --filter "dangling=true"
